# Configuration of the EST Server
Properties:
  # EST Service
  apiCustomDomainName: "YOUR API DOMAIN NAME HERE"
  apiCertificateArn: "YOUR API CERTIFICATE ARN from CERTIFICATE MANAGER HERE"
  apiOwnershipVerificationCertificateArn: "YOUR API OWNERSHIP VERIFICATION CERTIFICATE ARN from CERTIFICATE MANAGER HERE IF NECESSARY"
  # Enable or disable caller Headers
  apiStrictHeadersCheck: true
  # EST mTLS server side
  estMtlsCaSecretsName: "estMtlsCaSecrets"
  estMtlsCaCertValidity: 10
  # EST mTLS client side
  estMtlsClientSecretsName: "estMtlsClientSecrets"
  estMtlsClientPfxSecretName: "estMtlsClientPfx"
  estMtlsClientCertValidity: 10
  # IoT Core
  iotCoreEstCaCertSecretName: "estIotCoreCaSecretCert4"
  iotCoreEstCaKeySecretName: "estIotCoreCaSecretKey4"
  iotCoreEstCaValidityYears: 10
  iotTemplatePath: "config/iot_template_default.json"
  iotTemplateName: "est_iot_provisioning_template" # 36 characters max !!
  iotPolicyPath: "config/iot_policy_default.json"
  iotPolicyName: "est_iot_policy_default"
  iotDeviceCertValidityYears: 1
  # Lambda functions (applies to all. Log level can be modified individually with function environment variable)
  lambdaLoggerLevel: "INFO"
  lambdaTimeoutSeconds: 60
  # API Gateway
  apiGatewayIntegrationTimeoutSeconds: 30
  # Customization
  customSecretName: "customSecret"

DeploymentOptions:
  # mTLS Truststore certificate chain - generated if ""
  mTlsTruststoreCertificatesChainFile: "LOCAL PATH TO TRUST CHAIN PEM FILE"
  # Path to the IoT Core CA Certificate if provided or ""
  iotCoreCaCertificatePath: "LOCAL PATH TO CA CERTIFICATE FOR IOT DEVICES"
  # Path to the IoT Core CA Private Key if provided or ""
  iotCoreCaPrivateKeyPath: ""
  # Generates Iot Core self-signed certificate and private key for signing CSR
  # Ignored if iotCoreCaCertificatePath (above) is not ""
  generateIotCaCertificate: false
  # If 'true' IoT Core will be configured for JITP
  configureJITP: true
  # Tags that will be applied to the Stack and all resources
  tags:
    - key: "CostCenter"
      value: "My cost center"
    - key: "DeploymentEnvironment"
      value: "Demonstrator"
